
version: "3.9"

services:
  bresolin_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bresolin_app
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - bresolin_db
    volumes:
      - ./backend:/app

  bresolin_db:
    image: postgres:16
    container_name: bresolin_db
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
